Updating Nginx for new API.

diff --git a/nginx/bin/server/disable b/nginx/bin/server/disable
--- a/nginx/bin/server/disable
+++ b/nginx/bin/server/disable
@@ -7,17 +7,21 @@
 #
 true ${project:="${extension_args[0]:-$1}"}
 
-variable_is_nonempty project ||
-  fail "project must be specified for 'nginx server'"
-
-if file_exists "${service_config_path}/servers/$project.conf"
+if variable is empty project
 then
-  move_file "${service_config_path}/servers/$project.conf" \
+  fail "project must be specified for 'nginx server'"
+fi
+
+if files exist "${service_config_path}/servers/$project.conf"
+then
+  files move \
+    from "${service_config_path}/servers/$project.conf" \
     to "${service_config_path}/servers/$project.conf.disabled"
 else
-  file_exists "${service_config_path}/servers/$project.conf.disabled" ||
-    fail "INFO: Cannot disable"\
+  if ! files exist "${service_config_path}/servers/$project.conf.disabled"
+  then
+    fail "INFO: Cannot disable '${project}'"\
     "as ${service_config_path}/servers/$project.conf does not exist."
-
-  succeed "$project.conf is already disabled."
+  fi
+  succeed "$project.conf is disabled."
 fi
diff --git a/nginx/bin/server/enable b/nginx/bin/server/enable
--- a/nginx/bin/server/enable
+++ b/nginx/bin/server/enable
@@ -4,17 +4,22 @@
 # This moves /etc/nginx/projects/X.conf.disabled to X.conf
 true ${project:="${extension_args[0]:-$1}"}
 
-variable_is_nonempty project ||
-  fail "project must be specified for 'nginx project'"
-
-if file_exists "${service_config_path}/servers/$project.conf.disbled"
+if variable is empty project
 then
-  move_file "${service_config_path}/servers/$project.conf.disbled" \
+  fail "project must be specified for 'nginx project'"
+fi
+
+if files exist "${service_config_path}/servers/$project.conf.disbled"
+then
+  files move \
+    from "${service_config_path}/servers/$project.conf.disbled" \
     to "${service_config_path}/servers/$project.conf"
 else
-  file_exists "${service_config_path}/servers/$project.conf" ||
-    fail "Cannot disable, $project.conf"\
+  if ! files exist "${service_config_path}/servers/$project.conf"
+  then
+    fail "Cannot enable '$project'"\
       "as ${service_config_path}/servers/$project.conf.disabled does not exist."
+  fi
 
-  succeed "$project.conf is already enabled."
+  succeed "$project.conf is enabled."
 fi
