Cleaning up code for Nginx ext.

diff --git a/nginx/actions/server/disable b/nginx/actions/server/disable
--- a/nginx/actions/server/disable
+++ b/nginx/actions/server/disable
@@ -7,21 +7,17 @@
 #
 true ${project:="${extension_args[0]:-$1}"}
 
-if variable_is_nonempty project
-then
-  if file_exists "${service_config_path}/servers/$project.conf"
-  then
-    move_file "${service_config_path}/servers/$project.conf" \
-      to "${service_config_path}/servers/$project.conf.disabled"
-  else
-    if file_exists "${service_config_path}/servers/$project.conf.disabled"
-    then
-      succeed "$project.conf is already disabled."
-    else
-      fail "INFO: Cannot disable"\
-        "as ${service_config_path}/servers/$project.conf does not exist."
-    fi
-  fi
-else
+variable_is_nonempty project ||
   fail "project must be specified for 'nginx server'"
+
+if file_exists "${service_config_path}/servers/$project.conf"
+then
+  move_file "${service_config_path}/servers/$project.conf" \
+    to "${service_config_path}/servers/$project.conf.disabled"
+else
+  file_exists "${service_config_path}/servers/$project.conf.disabled" ||
+    fail "INFO: Cannot disable"\
+    "as ${service_config_path}/servers/$project.conf does not exist."
+
+  succeed "$project.conf is already disabled."
 fi
diff --git a/nginx/modules/shell/dsl b/nginx/modules/shell/dsl
--- a/nginx/modules/shell/dsl
+++ b/nginx/modules/shell/dsl
@@ -1,5 +1,55 @@
 #!/usr/bin/env bash
 
+nginx_initialize()
+{
+  # TODO: Allow overriding of these parameters via cli
+  # These defaults may be overridden also by the nginx configuration files.
+  configure_flags+=(
+  --prefix="${install_path}"
+  --conf-path="${install_path}/etc/nginx/nginx.conf"
+  --sbin-path="${install_path}/sbin/nginx"
+  --pid-path="${install_path}/run/nginx.pid"
+  --lock-path="${install_path}/run/nginx.lock"
+  --http-client-body-temp-path="${install_path}/spool/client_body_temp"
+  --http-proxy-temp-path="${install_path}/spool/proxy_temp"
+  --http-fastcgi-temp-path="${install_path}/spool/fastcgi_temp"
+  --http-log-path="${install_path}/log/access.log"
+  --error-log-path="${install_path}/log/error.log"
+  --with-http_ssl_module
+  --with-http_stub_status_module
+  )
+  # TODO: Add a CLI --imap flag
+  # --with-imap
+  # --with-imap_ssl_module
+
+  for library in zlib pcre # openssl
+  do
+    if package_is_active "$library"
+    then
+      configure_flags+=( --with-${library}="${packages_path}/${library}/active/src" )
+    fi
+  done
+  unset library
+
+  config_dirs=( conf servers users ssl )
+  nginx_dirs=( log spool run lock etc/nginx tmp )
+
+  nginx_files=( fastcgi.conf fastcgi.conf.default fastcgi_params
+  fastcgi_params.default koi-utf koi-win mime.types mime.types.default
+  nginx.conf.default scgi_params scgi_params.default uwsgi_params
+  uwsgi_params.default win-utf
+  )
+
+  LDFLAGS="-L${active_path}/lib ${LDFLAGS:-}"
+  CFLAGS="-I${active_path}/include ${CFLAGS:-} "
+
+  master_pid="$(ps auxww | awk '/[n]ginx: master/{print $2}' | head -1)"
+  service_flags=( -c "${service_config_path}/nginx.conf" )
+  service_binary="${active_path}/sbin/nginx"
+
+  user_is_not_root || service_run_as_root_flag=1
+}
+
 nginx_install_dependencies() {
 warn "${action} is untested / unused thus far."
 
@@ -52,32 +102,30 @@ nginx_postinstall()
    from "${install_path}/etc/nginx"
 
   ensure_paths_exist "${install_path}/config" "${install_path}/etc/nginx/servers"
-
 }
 
 nginx_postactivate()
 {
-  if user_is_root
+  user_is_root || return 0
+
+  if (( ${force_flag:=0} == 1 ))
   then
-    if (( ${force_flag:=0} == 1 ))
-    then
-      remove_paths "${service_config_path}"
-    fi
-
-    if ! file_exists "${service_config_path}/nginx.conf"
-    then
-      link --force "${install_base_path}/active/etc/nginx" \
-        "${service_config_path}"
-
-      enter "${service_config_path}"
-
-      # TODO: add from parameter from remove_files
-      remove_files "${nginx_files[@]}"
-    fi
-
-    link --force "${install_base_path}/active/sbin/nginx" \
-      "${active_path}/sbin/nginx"
+    remove_paths "${service_config_path}"
   fi
+
+  if ! file_exists "${service_config_path}/nginx.conf"
+  then
+    link --force "${install_base_path}/active/etc/nginx" \
+      "${service_config_path}"
+
+    enter "${service_config_path}"
+
+    # TODO: add from parameter from remove_files
+    remove_files "${nginx_files[@]}"
+  fi
+
+  link --force "${install_base_path}/active/sbin/nginx" \
+    "${active_path}/sbin/nginx"
 }
 
 
@@ -147,55 +195,4 @@ nginx_list()
   else
     log "No Nginx master processes was found."
   fi
-}
-
-
-nginx_initialize()
-{
-  # TODO: Allow overriding of these parameters via cli
-  # These defaults may be overridden also by the nginx configuration files.
-  configure_flags+=(
-  --prefix="${install_path}"
-  --conf-path="${install_path}/etc/nginx/nginx.conf"
-  --sbin-path="${install_path}/sbin/nginx"
-  --pid-path="${install_path}/run/nginx.pid"
-  --lock-path="${install_path}/run/nginx.lock"
-  --http-client-body-temp-path="${install_path}/spool/client_body_temp"
-  --http-proxy-temp-path="${install_path}/spool/proxy_temp"
-  --http-fastcgi-temp-path="${install_path}/spool/fastcgi_temp"
-  --http-log-path="${install_path}/log/access.log"
-  --error-log-path="${install_path}/log/error.log"
-  --with-http_ssl_module
-  --with-http_stub_status_module
-  )
-  # TODO: Add a CLI --imap flag
-  # --with-imap
-  # --with-imap_ssl_module
-
-  for library in zlib pcre # openssl
-  do
-    if package_is_active "$library"
-    then
-      configure_flags+=( --with-${library}="${packages_path}/${library}/active/src" )
-    fi
-  done
-  unset library
-
-  config_dirs=( conf servers users ssl )
-  nginx_dirs=( log spool run lock etc/nginx tmp )
-
-  nginx_files=( fastcgi.conf fastcgi.conf.default fastcgi_params
-  fastcgi_params.default koi-utf koi-win mime.types mime.types.default
-  nginx.conf.default scgi_params scgi_params.default uwsgi_params
-  uwsgi_params.default win-utf
-  )
-
-  LDFLAGS="-L${active_path}/lib ${LDFLAGS:-}"
-  CFLAGS="-I${active_path}/include ${CFLAGS:-} "
-
-  master_pid="$(ps auxww | awk '/[n]ginx: master/{print $2}' | head -1)"
-  service_flags=( -c "${service_config_path}/nginx.conf" )
-  service_binary="${active_path}/sbin/nginx"
-
-  user_is_not_root || service_run_as_root_flag=1
 }
